name: sitkpy

channels:
  - conda-forge

dependencies:
  - python=3.13
  - requests
  - jupyter
  - matplotlib
  - ipywidgets
  - ipympl
  - numpy
  - scipy
  - pandas
  - numba
  - multiprocess
  - tqdm
  - SimpleITK>3.0.0
